name: Sync Files
on:
  push:
    branches: [master]
jobs:
  test-echo:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: zardoy/sync-all@main
        with:
          config_file: repos.json
          github_token: ${{ secrets.sync_github_token }}
          commit_message: 'repos-sync: update files from %"SRC_REPO"%'
      # - name: get version
      #   id: version
      #   uses: notiz-dev/github-action-json-property@release
      #   with:
      #       path: 'repos.json'
      #       prop_path: 'test'
      # - run: echo ${{steps.version.outputs.prop}}
